var dribbblesMock = {
    page1: {
        "page": "1",
        "per_page": 2,
        "pages": 2,
        "total": 4,
        "shots": [
            {
                "id": 2033937,
                "title": "iOS Sign In",
                "description": "<p>Starting some initial interactions for signing in to confirm account and quick app walkthrough.</p>\n\n<p>Made with Quartz + Origami</p>\n\n<p>We are hiring product designers! https://dribbble.com/handsomemade/jobs</p>",
                "height": 600,
                "width": 800,
                "likes_count": 302,
                "comments_count": 17,
                "rebounds_count": 0,
                "url": "http://dribbble.com/shots/2033937-iOS-Sign-In",
                "short_url": "http://drbl.in/oykj",
                "views_count": 3815,
                "rebound_source_id": null,
                "image_url": "https://d13yacurqjgara.cloudfront.net/users/18730/screenshots/2033937/mkts_shot.gif",
                "image_teaser_url": "https://d13yacurqjgara.cloudfront.net/users/18730/screenshots/2033937/mkts_shot_teaser.gif",
                "image_400_url": "https://d13yacurqjgara.cloudfront.net/users/18730/screenshots/2033937/mkts_shot_1x.gif",
                "player": {
                    "id": 18730,
                    "name": "⋈ Sam Thibault ⋈",
                    "location": "Austin, TX",
                    "followers_count": 4356,
                    "draftees_count": 3,
                    "likes_count": 1878,
                    "likes_received_count": 20474,
                    "comments_count": 385,
                    "comments_received_count": 1013,
                    "rebounds_count": 3,
                    "rebounds_received_count": 4,
                    "url": "http://dribbble.com/SamuelATX",
                    "avatar_url": "https://d13yacurqjgara.cloudfront.net/users/18730/avatars/normal/sam_profile.png?1402637877",
                    "username": "SamuelATX",
                    "twitter_screen_name": "SamuelATX",
                    "website_url": "http://handsome.is",
                    "drafted_by_player_id": null,
                    "shots_count": 65,
                    "following_count": 896,
                    "created_at": "2011/02/18 00:31:59 -0500"
                },
                "created_at": "2015/04/24 02:36:46 -0400",
                "$$hashKey": "object:3"
            },
            {
                "id": 2034324,
                "title": "NPH",
                "description": "<p>Another secret shot for a secret thing. So many secrets these days.</p>",
                "height": 600,
                "width": 800,
                "likes_count": 209,
                "comments_count": 14,
                "rebounds_count": 0,
                "url": "http://dribbble.com/shots/2034324-NPH",
                "short_url": "http://drbl.in/oyrG",
                "views_count": 1054,
                "rebound_source_id": null,
                "image_url": "https://d13yacurqjgara.cloudfront.net/users/52758/screenshots/2034324/nph_dribbble.jpg",
                "image_teaser_url": "https://d13yacurqjgara.cloudfront.net/users/52758/screenshots/2034324/nph_dribbble_teaser.jpg",
                "image_400_url": "https://d13yacurqjgara.cloudfront.net/users/52758/screenshots/2034324/nph_dribbble_1x.jpg",
                "player": {
                    "id": 52758,
                    "name": "Jay Fletcher",
                    "location": "Charleston, SC",
                    "followers_count": 10342,
                    "draftees_count": 9,
                    "likes_count": 5712,
                    "likes_received_count": 68773,
                    "comments_count": 286,
                    "comments_received_count": 4147,
                    "rebounds_count": 166,
                    "rebounds_received_count": 264,
                    "url": "http://dribbble.com/jfletcherdesign",
                    "avatar_url": "https://d13yacurqjgara.cloudfront.net/users/52758/avatars/normal/J_FLETCHER_DESIGN_LOGO-01.jpg?1401983283",
                    "username": "jfletcherdesign",
                    "twitter_screen_name": "jfletcherdesign",
                    "website_url": "http://www.jfletcherdesign.com",
                    "drafted_by_player_id": 4018,
                    "shots_count": 376,
                    "following_count": 540,
                    "created_at": "2011/08/13 19:30:38 -0400"
                },
                "created_at": "2015/04/24 08:38:51 -0400",
                "$$hashKey": "object:4"
            }
        ]
    },
    page2: {
        "page": "2",
        "per_page": 2,
        "pages": 2,
        "total": 4,
        "shots": [
            {
                "id": 2034310,
                "title": "Lil' Dill",
                "description": "<p>Creating more animals out of geometric shapes that will hopefully become a series! Thanks to @[45617:David Kovalev] for the accidental suggestion of an armadillo. </p>\n\n<p>@2x for the good stuff</p>",
                "height": 600,
                "width": 800,
                "likes_count": 175,
                "comments_count": 16,
                "rebounds_count": 0,
                "url": "http://dribbble.com/shots/2034310-Lil-Dill",
                "short_url": "http://drbl.in/oyrs",
                "views_count": 967,
                "rebound_source_id": null,
                "image_url": "https://d13yacurqjgara.cloudfront.net/users/73294/screenshots/2034310/armadillo_final3.png",
                "image_teaser_url": "https://d13yacurqjgara.cloudfront.net/users/73294/screenshots/2034310/armadillo_final3_teaser.png",
                "image_400_url": "https://d13yacurqjgara.cloudfront.net/users/73294/screenshots/2034310/armadillo_final3_1x.png",
                "player": {
                    "id": 73294,
                    "name": "Ben Stafford",
                    "location": "Columbus, OH",
                    "followers_count": 2289,
                    "draftees_count": 4,
                    "likes_count": 11069,
                    "likes_received_count": 10740,
                    "comments_count": 1758,
                    "comments_received_count": 1223,
                    "rebounds_count": 9,
                    "rebounds_received_count": 14,
                    "url": "http://dribbble.com/BenStafford",
                    "avatar_url": "https://d13yacurqjgara.cloudfront.net/users/73294/avatars/normal/BenAvatar_Square.png?1398358134",
                    "username": "BenStafford",
                    "twitter_screen_name": "BenStafford86",
                    "website_url": "http://foxmeadowcreative.com",
                    "drafted_by_player_id": null,
                    "shots_count": 130,
                    "following_count": 608,
                    "created_at": "2011/11/04 13:52:31 -0400"
                },
                "created_at": "2015/04/24 08:29:02 -0400",
                "$$hashKey": "object:5"
            },
            {
                "id": 2034407,
                "title": "Amps",
                "description": "<p>Collection of ampersands I have made recently.</p>",
                "height": 600,
                "width": 800,
                "likes_count": 157,
                "comments_count": 5,
                "rebounds_count": 0,
                "url": "http://dribbble.com/shots/2034407-Amps",
                "short_url": "http://drbl.in/oytl",
                "views_count": 643,
                "rebound_source_id": null,
                "image_url": "https://d13yacurqjgara.cloudfront.net/users/52084/screenshots/2034407/amps.jpg",
                "image_teaser_url": "https://d13yacurqjgara.cloudfront.net/users/52084/screenshots/2034407/amps_teaser.jpg",
                "image_400_url": "https://d13yacurqjgara.cloudfront.net/users/52084/screenshots/2034407/amps_1x.jpg",
                "player": {
                    "id": 52084,
                    "name": "Steve Wolf",
                    "location": "Austin, Texas",
                    "followers_count": 7117,
                    "draftees_count": 7,
                    "likes_count": 670,
                    "likes_received_count": 33010,
                    "comments_count": 1137,
                    "comments_received_count": 2205,
                    "rebounds_count": 0,
                    "rebounds_received_count": 12,
                    "url": "http://dribbble.com/WOLF_STEVE",
                    "avatar_url": "https://d13yacurqjgara.cloudfront.net/users/52084/avatars/normal/ef07fd4b5e3d27774b8c077cc61d26d8.jpg?1411136929",
                    "username": "WOLF_STEVE",
                    "twitter_screen_name": "STEVEWOLFDESIGN",
                    "website_url": "http://stevewolf.co/",
                    "drafted_by_player_id": 18850,
                    "shots_count": 185,
                    "following_count": 747,
                    "created_at": "2011/08/10 15:36:38 -0400"
                },
                "created_at": "2015/04/24 09:35:20 -0400",
                "$$hashKey": "object:6"
            }
        ]
    }
};